import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient(process.env.TEST_DATABASE_URL ? { datasources: { db: { url: process.env.TEST_DATABASE_URL } } } : undefined);

const activities = [
  // Creative (1-25)
  { title: "Cook a dish from a country you can't point to on a map", description: "Spin a globe or pick a random nation, find a traditional recipe, and cook it from scratch.", category: "creative", energy: 3, budget: 3, social: 1, durationMin: 90 },
  { title: "Write a handwritten letter to your 80-year-old self", description: "Reflect on your current ambitions, fears, and hopes in ink.", category: "creative", energy: 1, budget: 1, social: 1, durationMin: 45 },
  { title: "Paint a canvas using only household items instead of brushes", description: "Use sponges, forks, credit cards, or leaves to create abstract art.", category: "creative", energy: 2, budget: 2, social: 1, durationMin: 60 },
  { title: "Compose and record a 30-second jingle about your favorite snack", description: "Use voice memos, tap rhythms on your table, and make a silly catchy song.", category: "creative", energy: 3, budget: 1, social: 1, durationMin: 30 },
  { title: "Design a custom board game using paper and cardboard", description: "Invent rules, draw a game map, and create tokens for a brand new game.", category: "creative", energy: 3, budget: 1, social: 2, durationMin: 120 },
  { title: "Bake artisanal sourdough bread from scratch", description: "Master kneading, proofing, and baking a golden crispy loaf.", category: "creative", energy: 2, budget: 2, social: 1, durationMin: 180 },
  { title: "Write a 500-word short story starting with a mystery prompt", description: "Let your imagination run wild starting with 'The door opened by itself...'", category: "creative", energy: 2, budget: 1, social: 1, durationMin: 40 },
  { title: "Build a mini terrarium inside a glass jar", description: "Collect moss, pebbles, soil, and small plants to create an enclosed ecosystem.", category: "creative", energy: 2, budget: 2, social: 1, durationMin: 60 },
  { title: "Fold 20 origami animals and hide them around your home", description: "Learn crane, frog, and dragon folds to create paper sculptures.", category: "creative", energy: 1, budget: 1, social: 1, durationMin: 45 },
  { title: "Create a zine about a niche hyper-fixation you have", description: "Fold paper into an 8-page mini magazine filled with illustrations and facts.", category: "creative", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Write a haiku poem for every room in your house", description: "Observe the vibes of kitchen, bedroom, and bathroom in 5-7-5 syllables.", category: "creative", energy: 1, budget: 1, social: 1, durationMin: 25 },
  { title: "Custom DIY tie-dye an old white T-shirt", description: "Twist, band, and dye an plain garment into vibrant swirling patterns.", category: "creative", energy: 3, budget: 2, social: 1, durationMin: 75 },
  { title: "Sculpt a miniature figurine out of clay or playdough", description: "Detail a tiny mythical creature or funny portrait.", category: "creative", energy: 2, budget: 2, social: 1, durationMin: 50 },
  { title: "Record a podcast episode monologue about a movie you love", description: "Review and analyze your favorite film like a professional broadcaster.", category: "creative", energy: 2, budget: 1, social: 1, durationMin: 35 },
  { title: "Create a stop-motion video using desk objects", description: "Take 50 photos moving items incrementally to animate a short clip.", category: "creative", energy: 3, budget: 1, social: 1, durationMin: 90 },
  { title: "Arrange a flower bouquet from wild blooms and greenery", description: "Practice floral composition using whatever grows outdoors.", category: "creative", energy: 2, budget: 1, social: 1, durationMin: 40 },
  { title: "Write a custom rap verse describing your typical morning", description: "Rhyme about alarm clocks, coffee, and rushing to get dressed.", category: "creative", energy: 3, budget: 1, social: 1, durationMin: 30 },
  { title: "Construct a LEGO structure without using instructions", description: "Build an architectural masterpiece purely out of spontaneous creativity.", category: "creative", energy: 2, budget: 2, social: 1, durationMin: 60 },
  { title: "Decorate a ceramic mug with porcelain paint pens", description: "Draw cute patterns or inspirational quotes on a plain white mug.", category: "creative", energy: 2, budget: 2, social: 1, durationMin: 45 },
  { title: "Knit or crochet a simple winter beanie or coaster", description: "Learn basic stitches and craft something cozy.", category: "creative", energy: 1, budget: 2, social: 1, durationMin: 120 },
  { title: "Craft a vision board out of magazine cutouts", description: "Collage your goals, dream destinations, and aesthetic inspiration.", category: "creative", energy: 1, budget: 1, social: 1, durationMin: 60 },
  { title: "Redesign the cover art of your favorite music album", description: "Draw or digitally design an alternative album cover art.", category: "creative", energy: 2, budget: 1, social: 1, durationMin: 50 },
  { title: "Try black-out poetry using an old newspaper page", description: "Black out words with a marker leaving behind poetic phrases.", category: "creative", energy: 1, budget: 1, social: 1, durationMin: 30 },
  { title: "Make homemade candles using soy wax and essential oils", description: "Melt wax, add soothing scents like lavender, and pour into glass containers.", category: "creative", energy: 2, budget: 3, social: 1, durationMin: 70 },
  { title: "Build a miniature cardboard castle for a pet or plushie", description: "Cut archways, towers, and draw brick textures on cardboard boxes.", category: "creative", energy: 3, budget: 1, social: 1, durationMin: 90 },

  // Fitness & Outdoor (26-60)
  { title: "Cold-plunge in the nearest body of water", description: "Take a bracing shock dip in a lake, ocean, or cold plunge tub.", category: "fitness", energy: 5, budget: 1, social: 2, durationMin: 20 },
  { title: "Sunrise high-intensity interval outdoor sprint session", description: "Wake up early and do 10 maximum-effort hill sprints as the sun rises.", category: "fitness", energy: 5, budget: 1, social: 1, durationMin: 40 },
  { title: "Go bouldering or indoor rock climbing", description: "Test your grip strength and solve physical climbing routes.", category: "fitness", energy: 4, budget: 3, social: 2, durationMin: 90 },
  { title: "Cycle 20 kilometers along a scenic trail", description: "Hop on a bicycle and explore nature paths at high speed.", category: "fitness", energy: 4, budget: 2, social: 2, durationMin: 120 },
  { title: "Attempt a 100 push-ups / 100 squats challenge", description: "Break it down into sets and push your physical endurance limit.", category: "fitness", energy: 4, budget: 1, social: 1, durationMin: 30 },
  { title: "Nighttime barefoot walk on grass or sand", description: "Ground yourself with sensory connection to nature under the stars.", category: "outdoor", energy: 2, budget: 1, social: 1, durationMin: 30 },
  { title: "Guided outdoor Vinyasa yoga practice in the park", description: "Flow through sun salutations while feeling the breeze.", category: "fitness", energy: 3, budget: 1, social: 2, durationMin: 45 },
  { title: "Rent a kayak or stand-up paddleboard on a lake", description: "Paddle across calm water and explore hidden coves.", category: "fitness", energy: 4, budget: 3, social: 2, durationMin: 90 },
  { title: "Participate in a local 5k park run", description: "Lace up your running shoes and join local runners.", category: "fitness", energy: 4, budget: 1, social: 3, durationMin: 45 },
  { title: "Geocaching adventure in your local city parks", description: "Use GPS coordinates to find hidden real-world treasure caches.", category: "outdoor", energy: 3, budget: 1, social: 2, durationMin: 90 },
  { title: "Hike to the highest elevation point within 10 miles", description: "Conquer a local summit and enjoy panoramic views.", category: "outdoor", energy: 4, budget: 1, social: 2, durationMin: 150 },
  { title: "Calisthenics workout at an outdoor fitness park", description: "Do pull-ups, dips, and muscle-up progressions on park bars.", category: "fitness", energy: 5, budget: 1, social: 1, durationMin: 50 },
  { title: "Go rollerblading or skateboarding along the boardwalk", description: "Cruise smooth pavements while feeling the wind.", category: "fitness", energy: 3, budget: 2, social: 2, durationMin: 60 },
  { title: "Learn 3 basic acrobatics or parkour vault moves", description: "Practice safety rolls, cat leaps, and precision jumps onto low ledges.", category: "fitness", energy: 4, budget: 1, social: 1, durationMin: 45 },
  { title: "Join an open pickup game of basketball or volleyball", description: "Head to a public court and join a casual friendly match.", category: "fitness", energy: 4, budget: 1, social: 4, durationMin: 90 },
  { title: "Trail running through a forest path", description: "Dodge tree roots and jump over streams on an off-road run.", category: "fitness", energy: 5, budget: 1, social: 1, durationMin: 45 },
  { title: "Foraging walk for edible herbs and berries", description: "Identify local plants using a guidebook or plant scanner app.", category: "outdoor", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Stargazing with a constellation map telescope app", description: "Lay out a blanket and identify planets and constellations.", category: "outdoor", energy: 1, budget: 1, social: 2, durationMin: 60 },
  { title: "Outdoor slacklining between two park trees", description: "Balance across a narrow flexible webbing line.", category: "fitness", energy: 3, budget: 2, social: 2, durationMin: 45 },
  { title: "Jump rope freestyle cardio session", description: "Master boxer steps, crossovers, and double-unders.", category: "fitness", energy: 4, budget: 1, social: 1, durationMin: 30 },
  { title: "Learn a 30-second viral dance routine", description: "Follow step-by-step video tutorials and get your heart pumping.", category: "fitness", energy: 3, budget: 1, social: 1, durationMin: 45 },
  { title: "Rent a city bike and explore a neighborhood you've never visited", description: "Be a tourist in your own city using bike lanes.", category: "outdoor", energy: 3, budget: 2, social: 2, durationMin: 120 },
  { title: "Go ice skating or roller skating at a rink", description: "Glide across smooth ice or hardwood with music playing.", category: "fitness", energy: 3, budget: 3, social: 3, durationMin: 75 },
  { title: "Shadowboxing workout with intense music beats", description: "Practice jab, cross, hook combinations and footwork.", category: "fitness", energy: 4, budget: 1, social: 1, durationMin: 35 },
  { title: "Birdwatching walk equipped with binoculars", description: "Spot and log 10 distinct species of birds.", category: "outdoor", energy: 2, budget: 2, social: 1, durationMin: 60 },
  { title: "Go disc golfing at a local course", description: "Throw frisbee discs into metal basket targets.", category: "outdoor", energy: 3, budget: 2, social: 3, durationMin: 100 },
  { title: "Swim laps at a local Olympic community pool", description: "Freestyle, backstroke, and breaststroke workout.", category: "fitness", energy: 4, budget: 2, social: 1, durationMin: 45 },
  { title: "Full body foam rolling and deep stretching session", description: "Relieve muscle tension and improve flexibility.", category: "fitness", energy: 1, budget: 1, social: 1, durationMin: 30 },
  { title: "Fly a stunt kite in an open field", description: "Control dual-line kites to loop and dive in strong wind.", category: "outdoor", energy: 3, budget: 2, social: 2, durationMin: 50 },
  { title: "Go beachcombing or riverbank treasure searching", description: "Find sea glass, interesting stones, or drift wood.", category: "outdoor", energy: 2, budget: 1, social: 2, durationMin: 80 },

  // Social & Group (61-95)
  { title: "Call a friend you haven't spoken to in 6+ months", description: "Catch up deeply on life, memories, and new adventures.", category: "social", energy: 2, budget: 1, social: 4, durationMin: 30 },
  { title: "Host a emergency thrift-store outfit dinner party", description: "Everyone buys a wacky \$5 outfit and wears it to dinner.", category: "social", energy: 4, budget: 2, social: 5, durationMin: 180 },
  { title: "Organize a board game tournament with friends", description: "Play Catan, Ticket to Ride, or Code Names for points.", category: "social", energy: 2, budget: 1, social: 4, durationMin: 150 },
  { title: "Host a DIY blind wine or chocolate tasting", description: "Wrap items in foil, grade them on paper, and guess the brands.", category: "social", energy: 2, budget: 3, social: 4, durationMin: 120 },
  { title: "Attend a local pub trivia night", description: "Form a team and test your knowledge on pop culture and history.", category: "social", energy: 3, budget: 2, social: 5, durationMin: 120 },
  { title: "Go to an open mic comedy show", description: "Cheer on brave comedians and laugh at unpolished jokes.", category: "social", energy: 2, budget: 2, social: 4, durationMin: 100 },
  { title: "Host a PowerPoint night where everyone presents on a random topic", description: "Present funny slideshows about absurd theories or personal lore.", category: "social", energy: 3, budget: 1, social: 5, durationMin: 150 },
  { title: "Go karaoke singing with a group of friends", description: "Belt out 90s hits and power ballads without judgment.", category: "social", energy: 4, budget: 3, social: 5, durationMin: 120 },
  { title: "Organize a neighborhood trash cleanup drive", description: "Grab gloves and trash bags to make local streets sparkle.", category: "social", energy: 3, budget: 1, social: 4, durationMin: 90 },
  { title: "Attend a local flea market or vintage pop-up", description: "Browse unique trinkets, retro clothes, and antique furniture.", category: "social", energy: 2, budget: 2, social: 3, durationMin: 90 },
  { title: "Host a homemade pizza making party", description: "Set out bowls of pepperoni, basil, cheeses, and bake custom pies.", category: "social", energy: 3, budget: 2, social: 5, durationMin: 120 },
  { title: "Go escape room decoding challenge", description: "Solve riddles and escape a themed locked room in 60 minutes.", category: "social", energy: 4, budget: 4, social: 4, durationMin: 75 },
  { title: "Gather around a campfire and tell ghost stories", description: "Roast marshmallows and share scary urban legends.", category: "social", energy: 2, budget: 2, social: 4, durationMin: 90 },
  { title: "Do a group photo walk in downtown", description: "Challenge each person to take 10 cool portraits of each other.", category: "social", energy: 3, budget: 1, social: 3, durationMin: 90 },
  { title: "Visit a local botanical garden or greenhouse", description: "Stroll through tropical plant exhibits and flower displays.", category: "social", energy: 2, budget: 2, social: 3, durationMin: 75 },
  { title: "Host a mystery movie marathon night", description: "Pick 3 movies blindly from different decades and watch together.", category: "social", energy: 1, budget: 1, social: 4, durationMin: 240 },
  { title: "Go laser tagging or paintballing", description: "Sprint through glowing obstacles and tag opponent teams.", category: "social", energy: 5, budget: 4, social: 5, durationMin: 90 },
  { title: "Take a group pottery or ceramics workshop", description: "Throw clay on a potter's wheel and glaze your creation.", category: "social", energy: 2, budget: 4, social: 3, durationMin: 120 },
  { title: "Attend a live local Indie band concert", description: "Support local musicians in an intimate basement venue.", category: "social", energy: 4, budget: 3, social: 4, durationMin: 150 },
  { title: "Host a book swap and discussion coffee hour", description: "Trade favorite pre-loved novels and discuss literary characters.", category: "social", energy: 1, budget: 1, social: 3, durationMin: 60 },
  { title: "Go bowling and wear hilarious retro shoes", description: "Aim for strikes and enjoy arcade vibes.", category: "social", energy: 3, budget: 2, social: 4, durationMin: 90 },
  { title: "Participate in a flash photography photobooth spree", description: "Find 3 photobooths in town and strike wacky poses.", category: "social", energy: 3, budget: 2, social: 2, durationMin: 60 },
  { title: "Host an international potluck dinner", description: "Each guest brings a dish representing a different country.", category: "social", energy: 2, budget: 2, social: 5, durationMin: 150 },
  { title: "Go to a local Farmers' Market tasting adventure", description: "Sample fresh jams, cheeses, sourdough, and organic fruits.", category: "social", energy: 2, budget: 2, social: 3, durationMin: 75 },
  { title: "Do an impromptu street performance or busking watch", description: "Enjoy local street musicians and tip your favorite acts.", category: "social", energy: 2, budget: 1, social: 3, durationMin: 45 },
  { title: "Host a video game couch co-op tournament", description: "Play Overcooked, Smash Bros, or Mario Kart together.", category: "social", energy: 3, budget: 1, social: 4, durationMin: 120 },
  { title: "Volunteer at a local animal shelter or food bank", description: "Walk rescue dogs or pack meals for families in need.", category: "social", energy: 3, budget: 1, social: 4, durationMin: 180 },
  { title: "Go mini-golfing at an arcade course", description: "Putt around windmills, castles, and water hazards.", category: "social", energy: 2, budget: 2, social: 3, durationMin: 60 },
  { title: "Host a mocktail mixology workshop", description: "Mix sparkling waters, syrups, herbs, and fresh fruit juices.", category: "social", energy: 2, budget: 2, social: 4, durationMin: 60 },
  { title: "Attend a community outdoor movie screening", description: "Bring lawn chairs and popcorn under the summer night sky.", category: "social", energy: 1, budget: 1, social: 4, durationMin: 120 },
  { title: "Go on a street food crawl down a famous avenue", description: "Try tacos, dumplings, churros, and kebabs from food trucks.", category: "social", energy: 3, budget: 3, social: 4, durationMin: 90 },
  { title: "Play frisbee golf or ultimate frisbee in the park", description: "Run and toss frisbees in team passing games.", category: "social", energy: 4, budget: 1, social: 4, durationMin: 75 },
  { title: "Organize a garage sale or clothing swap pop-up", description: "De-clutter your closet and trade clothes with friends.", category: "social", energy: 3, budget: 1, social: 4, durationMin: 180 },
  { title: "Attend a salsa or bachata dance social class", description: "Learn basic Latin dance steps with a partner.", category: "social", energy: 4, budget: 2, social: 5, durationMin: 90 },
  { title: "Go on a scenic sunset drive with a custom playlist", description: "Play your favorite tunes while cruising country roads.", category: "social", energy: 2, budget: 2, social: 2, durationMin: 60 },

  // Solo & Relaxation (96-140)
  { title: "Digital detox: 4 hours without any screens", description: "Turn off phone, TV, computer, and read or meditate instead.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 240 },
  { title: "Deep acoustic sound bath meditation", description: "Listen to singing bowls and ambient frequency soundscapes.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 45 },
  { title: "Create a luxurious Spa Day at home", description: "Face mask, foot soak, cucumber water, and warm bath oils.", category: "relaxation", energy: 1, budget: 2, social: 1, durationMin: 90 },
  { title: "Read 50 pages of a novel in a cozy coffee shop", description: "Sip a hot cappuccino while getting lost in a chapter book.", category: "solo", energy: 1, budget: 2, social: 1, durationMin: 75 },
  { title: "Listen to an entire album from start to finish with eyes closed", description: "No distractions, no skipping tracks, pure active music listening.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 50 },
  { title: "Solo date: Eat at a restaurant counter alone without checking your phone", description: "Savor your food and people-watch mindfully.", category: "solo", energy: 2, budget: 3, social: 1, durationMin: 60 },
  { title: "Write down 50 things you are deeply grateful for", description: "Express gratitude for small details, memories, and people.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 30 },
  { title: "Re-organize and color-coordinate your wardrobe", description: "Declutter unworn items and fold clothing neatly.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 90 },
  { title: "Take a 30-minute hot Epsom salt bubble bath", description: "Light candles, turn off bright overhead lights, and soak.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 35 },
  { title: "Explore an art museum or gallery solo", description: "Pace yourself through exhibits and admire paintings quietly.", category: "solo", energy: 2, budget: 2, social: 1, durationMin: 120 },
  { title: "Guided progressive muscle relaxation exercise", description: "Tense and release every muscle group from toes to head.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 20 },
  { title: "Write a detailed life inventory and personal goal map", description: "Evaluate career, health, relationships, and financial milestones.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Listen to a philosophy podcast while taking a long walk", description: "Contemplate Stoicism, Existentialism, or Eastern philosophies.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Watch a classic black-and-white movie from the 1950s", description: "Experience cinema history with classic film noir or comedy.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 110 },
  { title: "Practice breathwork: 4-7-8 calming breathing technique", description: "Inhale for 4s, hold for 7s, exhale for 8s for 15 cycles.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 15 },
  { title: "Visit a local public library and browse random non-fiction shelves", description: "Pick a book on a topic you know nothing about and read chapter 1.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 60 },
  { title: "Build an elaborate blanket and pillow fort in your living room", description: "Use chairs, sheets, cushions, and fairy lights for ultimate coziness.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 45 },
  { title: "Do a 500-piece jigsaw puzzle with ambient rain sounds playing", description: "Find corner pieces and piece together a beautiful puzzle image.", category: "solo", energy: 1, budget: 2, social: 1, durationMin: 120 },
  { title: "Write a letter to a person who impacted your life, without sending it", description: "Process feelings of gratitude, closure, or forgiveness.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 30 },
  { title: "Spend 30 minutes stargazing from your balcony or roof", description: "Watch for shooting stars and satellites in total tranquility.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 30 },
  { title: "Make a bucket list of 100 places to visit before you die", description: "Research remote islands, ancient ruins, and vibrant cities.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 45 },
  { title: "Practice mindfulness meditation in a quiet corner", description: "Focus gently on the sensation of your breath coming in and out.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 20 },
  { title: "Clean and detail your laptop, keyboard, and phone case", description: "Sanitize screens, blow out dust, and polish devices.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 30 },
  { title: "Try journaling stream-of-consciousness for 3 pages", description: "Write whatever comes to mind without editing or censoring.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 25 },
  { title: "Brew a pot of loose-leaf herbal tea and sip mindfully", description: "Savor chamomile, peppermint, or jasmine tea slowly.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 30 },
  { title: "Take a scenic train ride to the end of the line and back", description: "Watch landscapes pass by out the window.", category: "solo", energy: 1, budget: 3, social: 1, durationMin: 120 },
  { title: "Cloud-watching in a grassy park field", description: "Lay on your back and identify shapes in floating clouds.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 40 },
  { title: "Curate a 50-song thematic playlist for your next road trip", description: "Discover new artists and organize smooth transitions.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Visit an aquarium and watch jellyfish swim", description: "Enjoy mesmerization from glowing marine life under dark blue light.", category: "solo", energy: 1, budget: 3, social: 1, durationMin: 90 },
  { title: "Organize all your digital photos into clean folders by year", description: "Back up memories, delete duplicates, and tag favorite moments.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 90 },
  { title: "Learn self-massage techniques for neck and shoulder strain", description: "Use tennis balls or acupressure to release upper body knot tightness.", category: "relaxation", energy: 1, budget: 1, social: 1, durationMin: 25 },
  { title: "Write a poem describing your favorite childhood memory", description: "Capture scents, sounds, and emotions of long ago.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 35 },
  { title: "Watch a high-definition nature documentary about deep oceans", description: "Marvel at bioluminescent creatures in the abyss.", category: "solo", energy: 1, budget: 1, social: 1, durationMin: 60 },
  { title: "Plant herbs (basil, mint, rosemary) in small windowsill pots", description: "Soil your hands, plant seeds, and water your new kitchen herb garden.", category: "solo", energy: 2, budget: 2, social: 1, durationMin: 45 },
  { title: "Do a digital declutter: unsubscribe from 20 marketing emails", description: "Clean out your inbox and revoke unused app permissions.", category: "solo", energy: 2, budget: 1, social: 1, durationMin: 30 },

  // Culinary & Foodie (141-175)
  { title: "Make fresh pasta noodles from flour and eggs by hand", description: "Form a flour well, mix eggs, roll thin sheets, and cut fettuccine.", category: "culinary", energy: 3, budget: 2, social: 2, durationMin: 90 },
  { title: "Bake French macarons with flavored ganache filling", description: "Whip egg whites, fold almond flour, and achieve perfect cookie feet.", category: "culinary", energy: 3, budget: 3, social: 1, durationMin: 120 },
  { title: "Craft artisanal hand-shaken cocktails/mocktails", description: "Muddle mint, shake with ice, and garnish like a master bartender.", category: "culinary", energy: 2, budget: 3, social: 2, durationMin: 40 },
  { title: "Ferment your own jar of spicy kimchi or sauerkraut", description: "Chop cabbage, salt, season with chili powder, and ferment.", category: "culinary", energy: 3, budget: 2, social: 1, durationMin: 75 },
  { title: "Make authentic Japanese ramen broth from scratch", description: "Simmer aromatic bones, kombu, and garlic for rich savory broth.", category: "culinary", energy: 3, budget: 3, social: 2, durationMin: 240 },
  { title: "Host a homemade sushi rolling challenge", description: "Season sushi rice, lay nori sheets, roll salmon, avocado, and cucumber.", category: "culinary", energy: 3, budget: 3, social: 3, durationMin: 90 },
  { title: "Make gourmet French crepe pancakes with sweet fillings", description: "Whisk paper-thin batter and top with Nutella, strawberries, and cream.", category: "culinary", energy: 2, budget: 2, social: 2, durationMin: 45 },
  { title: "Bake soft pretzel twists dipped in warm beer cheese sauce", description: "Proof yeast dough, twist into pretzels, boil in baking soda, and bake.", category: "culinary", energy: 3, budget: 2, social: 2, durationMin: 90 },
  { title: "Prepare slow-cooked Indian chicken tikka masala", description: "Marinate in yogurt and spices, grill, and simmer in creamy tomato gravy.", category: "culinary", energy: 3, budget: 3, social: 2, durationMin: 120 },
  { title: "Make homemade ice cream or fruit sorbet without a machine", description: "Whip heavy cream and condensed milk, freeze, and enjoy smooth scoops.", category: "culinary", energy: 2, budget: 2, social: 1, durationMin: 60 },
  { title: "Cook authentic Spanish seafood paella in a wide skillet", description: "Saffron rice, shrimp, mussels, and chorizo cooked until golden crust forms.", category: "culinary", energy: 4, budget: 4, social: 4, durationMin: 100 },
  { title: "Smoke or slow-roast BBQ pulled pork or jackfruit", description: "Spice rub and slow roast for 6 hours until tender shredded perfection.", category: "culinary", energy: 2, budget: 3, social: 3, durationMin: 360 },
  { title: "Make homemade gnocchi from boiled potatoes", description: "Mash potatoes, mix with flour, ridge on a fork, and boil.", category: "culinary", energy: 3, budget: 2, social: 2, durationMin: 75 },
  { title: "Bake a multi-layer chocolate fudge cake with ganache", description: "Rich cocoa sponge layers frosted with decadent chocolate icing.", category: "culinary", energy: 3, budget: 3, social: 2, durationMin: 110 },
  { title: "Craft hand-folded dumplings or potstickers", description: "Pinch pleated wrappers filled with seasoned pork or veggies and pan-fry.", category: "culinary", energy: 3, budget: 2, social: 3, durationMin: 90 },
  { title: "Make a charcuterie board with fancy cheeses and fruits", description: "Arrange brie, prosciutto, figs, crackers, and honey artfully.", category: "culinary", energy: 2, budget: 4, social: 3, durationMin: 40 },
  { title: "Brew your own cold brew coffee concentrate", description: "Coarse grind beans, steep in cold water for 18 hours, and strain.", category: "culinary", energy: 1, budget: 2, social: 1, durationMin: 30 },
  { title: "Cook authentic Mexican street tacos with homemade salsa verde", description: "Roast tomatillos, press corn tortillas, and sear marinated meat.", category: "culinary", energy: 3, budget: 2, social: 3, durationMin: 70 },
  { title: "Bake cinnamon rolls with cream cheese glaze from scratch", description: "Roll cinnamon sugar in yeast dough, bake soft rolls, and smother in icing.", category: "culinary", energy: 3, budget: 2, social: 2, durationMin: 120 },
  { title: "Make homemade bubble boba tea with tapioca pearls", description: "Boil brown sugar boba pearls and pour milk tea over ice.", category: "culinary", energy: 2, budget: 2, social: 2, durationMin: 35 },
  { title: "Prepare traditional French onion soup with melty Gruyère toast", description: "Caramelize onions for an hour, deglaze with wine, and broil cheese tops.", category: "culinary", energy: 3, budget: 3, social: 2, durationMin: 90 },
  { title: "Make homemade churros dusted with cinnamon sugar and chocolate dip", description: "Pipe choux pastry into hot oil and coat in sparkling sugar.", category: "culinary", energy: 3, budget: 2, social: 2, durationMin: 50 },
  { title: "Bake classic Italian focaccia bread with rosemary and sea salt", description: "Dimple olive-oil rich dough with fingertips and sprinkle herbs.", category: "culinary", energy: 2, budget: 2, social: 2, durationMin: 120 },
  { title: "Create a homemade hot sauce blend using fresh chilies", description: "Blend habaneros, garlic, vinegar, and fruits into spicy bottle sauces.", category: "culinary", energy: 2, budget: 2, social: 1, durationMin: 45 },
  { title: "Make fresh mozzarella cheese from milk and rennet", description: "Heat milk, curdle, stretch cheese in hot water, and form smooth balls.", category: "culinary", energy: 3, budget: 3, social: 2, durationMin: 60 },
  { title: "Cook authentic Thai Green Curry with coconut milk and bamboo shoots", description: "Pound green curry paste, simmer coconut cream, and toss fresh basil.", category: "culinary", energy: 3, budget: 3, social: 2, durationMin: 50 },
  { title: "Bake fruit galette rustic tart", description: "Fold pie crust edges over peaches or berries and bake until bubbly.", category: "culinary", energy: 2, budget: 2, social: 2, durationMin: 60 },
  { title: "Make homemade hummus with crispy roasted chickpeas", description: "Blend tahini, lemon, garlic, chickpeas into ultra-creamy dip.", category: "culinary", energy: 2, budget: 1, social: 1, durationMin: 25 },
  { title: "Cook Middle Eastern Shakshuka with poached eggs", description: "Simmer cumin-spiced tomato bell pepper sauce and break eggs into wells.", category: "culinary", energy: 2, budget: 2, social: 2, durationMin: 35 },
  { title: "Infuse your own cooking oils with garlic, chili, and herbs", description: "Bottle extra virgin olive oil with dried herbs and chili flakes.", category: "culinary", energy: 1, budget: 2, social: 1, durationMin: 20 },
  { title: "Bake classic fudgy brownies with cracked shiny tops", description: "Melt dark chocolate and butter for dense rich brownie squares.", category: "culinary", energy: 2, budget: 2, social: 2, durationMin: 45 },
  { title: "Make homemade pasta carbonara with guanciale and egg yolks", description: "Emulsify pasta water, pecorino romano, and egg yolk into silky sauce.", category: "culinary", energy: 2, budget: 3, social: 2, durationMin: 30 },
  { title: "Make homemade falafel balls with tahini sauce", description: "Soak chickpeas, grind with herbs, shape balls, and deep fry.", category: "culinary", energy: 3, budget: 2, social: 2, durationMin: 60 },
  { title: "Bake traditional English scones served with clotted cream and jam", description: "Cut buttery dough, bake golden, and serve with hot afternoon tea.", category: "culinary", energy: 2, budget: 2, social: 2, durationMin: 45 },
  { title: "Make Vietnamese Pho beef noodle soup broth from scratch", description: "Char ginger and onions, toast star anise, and simmer fragrant broth.", category: "culinary", energy: 3, budget: 3, social: 2, durationMin: 180 },

  // Learning & Gaming & Novelty (176-200)
  { title: "Learn to solve a 3x3 Rubik's Cube using beginner method", description: "Memorize layer-by-layer algorithms and solve your first cube.", category: "learning", energy: 3, budget: 2, social: 1, durationMin: 90 },
  { title: "Master 5 essential rope knots (Bowline, Clove Hitch, Figure 8)", description: "Practice tying utility knots with a piece of paracord.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 40 },
  { title: "Learn the Morse code alphabet and send a secret message", description: "Practice dots and dashes for letters A-Z.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 45 },
  { title: "Play an indie puzzle video game with a captivating storyline", description: "Immerse yourself in games like Portal, Celeste, or Baba Is You.", category: "gaming", energy: 2, budget: 2, social: 1, durationMin: 120 },
  { title: "Learn 10 phrases in sign language (ASL)", description: "Learn greetings, alphabet spelling, and common conversational signs.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 35 },
  { title: "Practice basic speed-reading techniques", description: "Use pointer methods and eliminate sub-vocalization to double reading speed.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 30 },
  { title: "Learn 3 slick sleight-of-hand card magic tricks", description: "Practice double lifts, false cuts, and card forces.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Study basic astronomy: identify 5 major constellations", description: "Learn to spot Orion, Ursa Major, Cassiopeia, and Pegasus.", category: "learning", energy: 1, budget: 1, social: 1, durationMin: 30 },
  { title: "Speedrun a classic retro video game level", description: "Time yourself attempting a flawless run in Super Mario or Sonic.", category: "gaming", energy: 3, budget: 1, social: 1, durationMin: 45 },
  { title: "Learn to juggle 3 tennis balls continuously", description: "Master the 3-ball cascade throwing pattern.", category: "learning", energy: 3, budget: 1, social: 1, durationMin: 45 },
  { title: "Study basic financial literacy: understand index funds and compound interest", description: "Read up on passive investing and financial independence formulas.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Learn the phonetic military alphabet (Alpha, Bravo, Charlie)", description: "Memorize A-Z NATO phonetic code words for crisp communication.", category: "learning", energy: 1, budget: 1, social: 1, durationMin: 20 },
  { title: "Play a solo tabletop RPG game module", description: "Roll dice and follow branching story paths in a solo adventure book.", category: "gaming", energy: 2, budget: 2, social: 1, durationMin: 90 },
  { title: "Learn basic lock-picking on a transparent practice padlock", description: "Understand tension wrenches and pin tumblers mechanically.", category: "learning", energy: 2, budget: 2, social: 1, durationMin: 45 },
  { title: "Master chess opening principles and play 3 online rapid games", description: "Control the center, develop pieces, and safeguard your king.", category: "gaming", energy: 3, budget: 1, social: 1, durationMin: 60 },
  { title: "Learn to identify 10 local tree species by leaf and bark", description: "Differentiate oak, maple, birch, pine, and ash trees.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 45 },
  { title: "Learn 5 basic phrases in 5 different foreign languages", description: "Say hello and thank you in Japanese, French, Swahili, Arabic, and Italian.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 30 },
  { title: "Try touch typing exercises to reach 80+ words per minute", description: "Practice home row finger placement on typing test websites.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 30 },
  { title: "Learn memory techniques: build a 'Mind Palace' for 20 items", description: "Use spatial memory to recall a list of items in exact order.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 40 },
  { title: "Watch a 30-minute TED talk about human psychology or neuroscience", description: "Discover how habits form or how memory works in the brain.", category: "learning", energy: 1, budget: 1, social: 1, durationMin: 35 },
  { title: "Learn basic first aid & CPR steps", description: "Understand Heimlich maneuver, wound bandaging, and recovery position.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 45 },
  { title: "Play an interactive text adventure game in the terminal", description: "Experience classic Zork-style interactive fiction.", category: "gaming", energy: 2, budget: 1, social: 1, durationMin: 60 },
  { title: "Learn basic palmistry or tarot card reading fundamentals", description: "Study heart, head, and life lines or major arcana symbolism.", category: "learning", energy: 1, budget: 1, social: 1, durationMin: 45 },
  { title: "Practice whistling loudly using two fingers", description: "Find the tongue placement and air angle for piercing whistles.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 25 },
  { title: "Learn to read music sheet notation for treble clef", description: "Identify notes E-G-B-D-F and FACE on musical staves.", category: "learning", energy: 2, budget: 1, social: 1, durationMin: 40 }
];

async function main() {
  console.log('Seeding activities...');
  // Preserve existing matches and swipes when seeding again.
  
  for (const activity of activities) {
    const existing = await prisma.activity.findFirst({ where: { title: activity.title } });
    if (!existing) await prisma.activity.create({ data: activity });
  }
  
  console.log(`Successfully seeded ${activities.length} activities!`);
}

main()
  .catch((e) => {
    console.error('Error seeding data:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
